### PR TITLE
Server status

### PR DESCRIPTION
**Pull request by namila007**
## Pull Request for Issue #
issue #24 
## Description
simple server status 
## Testing instructions
run GET to relevant end point

### CODE REVIEW

**Comment by namila007** [comment]
clone n give a run, git repso should mount i think

**Comment by namila007** [comment]
that git code is for linux bash, thats why, not working on windows 
``` bash
#!/bin/bash

branch_name="$(git symbolic-ref HEAD 2>/dev/null)" ||
branch_name="(unnamed branch)" # detached HEAD
branch_name=${branch_name##refs/heads/}

git_sha=`git rev-parse HEAD`

echo $branch_name,$git_sha 
```

**Comment by namila007** [comment]
removing this due to server crash

**Comment by kasvith** [comment]
Since this is not that prioritized we can leave this for now
That git command is not useful for us

**Pull request closed without merging**
